// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs6VKxFfOvQ6PTvF-LE9lPgvAIe4Zx5uc',
    appId: '1:15161561940:web:ddc01b6f3bd2f71bd22ec1',
    messagingSenderId: '15161561940',
    projectId: 'ecommerce-01010',
    authDomain: 'ecommerce-01010.firebaseapp.com',
    storageBucket: 'ecommerce-01010.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1_YWRORZAXVo8nFoUSrMTWVwOxXYX4hk',
    appId: '1:15161561940:android:9bf6a81b43beef0bd22ec1',
    messagingSenderId: '15161561940',
    projectId: 'ecommerce-01010',
    storageBucket: 'ecommerce-01010.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi0zED4a9gV9P0FA3bFUYR6UK4bfywb2g',
    appId: '1:15161561940:ios:0a8ad0e44eb70bbad22ec1',
    messagingSenderId: '15161561940',
    projectId: 'ecommerce-01010',
    storageBucket: 'ecommerce-01010.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAppWithFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi0zED4a9gV9P0FA3bFUYR6UK4bfywb2g',
    appId: '1:15161561940:ios:0a8ad0e44eb70bbad22ec1',
    messagingSenderId: '15161561940',
    projectId: 'ecommerce-01010',
    storageBucket: 'ecommerce-01010.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAppWithFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs6VKxFfOvQ6PTvF-LE9lPgvAIe4Zx5uc',
    appId: '1:15161561940:web:8a331980a4fe9ffbd22ec1',
    messagingSenderId: '15161561940',
    projectId: 'ecommerce-01010',
    authDomain: 'ecommerce-01010.firebaseapp.com',
    storageBucket: 'ecommerce-01010.firebasestorage.app',
  );
}
